### ISSUE TITLE
Unable to compile 

### ISSUE THREAD

**Issue by Jonesee** [rickyzhang82/bREST#2]
I'm making an effort to use this library with an Ethernet shield instead of the Wifi adapter.
I've made all of the the appropriate changes in the sketch, but when I compile the sketch, I get the following error:
 _C:\Users\Wes\Documents\Arduino\libraries\bREST-master/bREST.h:202:13: error: 'virtual bREST::~bREST()' marked 'override', but does not override_ along with some other errors referencing override issues. 
I'd really like to get this working but at this point I'm somewhat stumped...

**Comment by rickyzhang82** [comment]
Make sure remove any installed aREST library.

**Comment by Jonesee** [comment]
Thanks for your prompt reply-that solved the issue. And thank you for posting your code, it's exactly what I need!
